language: java
arch:
  - amd64
  - ppc64le
jdk:
  - openjdk7
  - oraclejdk8
  - openjdk11

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - kama@soebes.de
